create table compagny (societe_id bigint generated by default as identity (start with 1), name varchar(50) not null, vatnumber varchar(255) not null, primary key (societe_id))
create table employee (employee_id bigint generated by default as identity (start with 1), age integer not null, first_name varchar(50) not null, last_name varchar(50) not null, compagny_societe_id bigint, primary key (employee_id))
alter table employee add constraint FKkmjrx9vdqyio4h84i4kvjwdxe foreign key (compagny_societe_id) references compagny
